#!/usr/bin/env bash
# shell-setup installer
# Run on a fresh macOS machine to install the whole stack.
#
# Usage:
#   cd ~/path/to/shell-setup
#   ./install.sh
#
# What it does:
#   1. Installs Homebrew if missing
#   2. Installs all CLI tools + fonts from Brewfile
#   3. Symlinks configs into ~/.config and home dir
#   4. Sets up Catppuccin Latte as the default theme
#   5. Configures git delta as the diff viewer
#
# Idempotent: re-run safely. Existing dotfiles get backed up to .bak.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"

say() { printf "\033[1;34m▸\033[0m %s\n" "$*"; }
ok()  { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
warn(){ printf "\033[1;33m!\033[0m %s\n" "$*"; }
err() { printf "\033[1;31m✗\033[0m %s\n" "$*" >&2; }

# ── 1. macOS check ─────────────────────────────────────
if [[ "$(uname)" != "Darwin" ]]; then
  err "This installer is macOS-only."
  exit 1
fi

# ── 2. Homebrew ────────────────────────────────────────
if ! command -v brew >/dev/null; then
  say "Installing Homebrew…"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  # Add brew to PATH for current shell on Apple Silicon
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  ok "Homebrew already installed"
fi

# ── 3. Brewfile (CLI tools + fonts + Kitty) ───────────
say "Installing tools from Brewfile (this takes a few minutes on first run)…"
brew bundle --file="$REPO_DIR/Brewfile"
ok "Brewfile installed"

# ── 4. Backup + symlink dotfiles ──────────────────────
backup_and_link() {
  local src="$1"
  local dest="$2"
  if [[ -e "$dest" && ! -L "$dest" ]]; then
    warn "Backing up existing $dest → $dest.bak-$TIMESTAMP"
    mv "$dest" "$dest.bak-$TIMESTAMP"
  elif [[ -L "$dest" ]]; then
    rm "$dest"
  fi
  mkdir -p "$(dirname "$dest")"
  ln -s "$src" "$dest"
  ok "Linked $dest → $src"
}

say "Linking dotfiles…"

# Home-directory file
backup_and_link "$REPO_DIR/home/.zshrc"            "$HOME/.zshrc"

# Config-directory files
backup_and_link "$REPO_DIR/config/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"
backup_and_link "$REPO_DIR/config/kitty/themes"     "$HOME/.config/kitty/themes"
backup_and_link "$REPO_DIR/config/starship.toml"    "$HOME/.config/starship.toml"
backup_and_link "$REPO_DIR/config/theme/theme.zsh"  "$HOME/.config/theme/theme.zsh"

# ── 5. Initial theme: Catppuccin Latte ────────────────
say "Setting initial theme to Catppuccin Latte…"
mkdir -p "$HOME/.config/theme"
cat > "$HOME/.config/theme/active.zsh" <<'EOF'
# Auto-generated by install.sh — current: latte
export BAT_THEME="Catppuccin Latte"
export LS_COLORS="$(vivid generate catppuccin-latte)"
export FZF_DEFAULT_OPTS="--color=bg+:#ccd0da,bg:#eff1f5,spinner:#dc8a78,hl:#d20f39,fg:#4c4f69,header:#d20f39,info:#8839ef,pointer:#dc8a78,marker:#7287fd,fg+:#4c4f69,prompt:#8839ef,hl+:#d20f39,selected-bg:#bcc0cc,border:#ccd0da,label:#4c4f69"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#9ca0b0'

typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg=#4c4f69'
ZSH_HIGHLIGHT_STYLES[command]='fg=#40a02b'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#40a02b'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#179299'
ZSH_HIGHLIGHT_STYLES[function]='fg=#1e66f5'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#fe640b,underline'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#d20f39,bold'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#6c6f85,italic'
ZSH_HIGHLIGHT_STYLES[path]='fg=#1e66f5,underline'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#fe640b'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#fe640b'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#df8e1d'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#7287fd'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#8839ef'
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=#d20f39,bold'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=#179299,underline'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#df8e1d'
EOF
ok "Active theme set to Latte (change later with: theme nord / theme one)"

# ── 6. Git delta config ───────────────────────────────
say "Configuring git delta as diff viewer…"
git config --global core.pager "delta"
git config --global interactive.diffFilter "delta --color-only"
git config --global delta.navigate true
git config --global delta.line-numbers true
git config --global delta.light true
git config --global delta.syntax-theme "Catppuccin Latte"
git config --global merge.conflictstyle "zdiff3"
ok "Git delta configured"

# ── 7. tldr cache ─────────────────────────────────────
say "Pulling tldr cheatsheet cache…"
tldr --update >/dev/null 2>&1 || true
ok "tldr ready"

# ── 8. Secrets template ───────────────────────────────
if [[ ! -f "$HOME/.zshenv.local" ]]; then
  cp "$REPO_DIR/home/.zshenv.local.example" "$HOME/.zshenv.local"
  warn "Created ~/.zshenv.local from template — edit it to add any API tokens"
fi

# ── 9. Bottom config dir ──────────────────────────────
mkdir -p "$HOME/.config/bottom" "$HOME/.config/tealdeer" "$HOME/.config/lazygit"

echo
ok "Done. Next steps:"
echo "  1. Open a new Kitty window (the theme + font load on startup)"
echo "  2. Run: theme list             # see available themes"
echo "  3. Run: theme cat              # switch to Catppuccin Latte (default)"
echo "  4. (Optional) edit ~/.zshenv.local to add API tokens"
echo "  5. Read docs/LEARN-TO-SH.md for daily-training exercises"
echo
echo "If your terminal still looks bare:"
echo "  exec zsh                       # re-execute zsh in the current shell"
